Add the full option for larger test case

diff --git a/scripts/RUN_TEST b/scripts/RUN_TEST
--- a/scripts/RUN_TEST
+++ b/scripts/RUN_TEST
@@ -15,8 +15,8 @@ fi
 # return text in green, bold
 pass-style() {
     if [ $# -ne 1 ]; then
-        echo "Usage: pass-style <text>"  
-    else 
+        echo "Usage: pass-style <text>"
+    else
         echo -e "\033[1;32m$1\033[0m"
     fi
 }
@@ -25,8 +25,8 @@ export -f pass-style
 # return text in red, bold
 fail-style() {
     if [ $# -ne 1 ]; then
-        echo "Usage: fail-style <text>"  
-    else 
+        echo "Usage: fail-style <text>"
+    else
         echo -e "\033[1;31m$1\033[0m"
     fi
 }
@@ -35,8 +35,8 @@ export -f fail-style
 # return text in cyan, bold
 unknown-style() {
     if [ $# -ne 1 ]; then
-        echo "Usage: unknown-style <text>"  
-    else 
+        echo "Usage: unknown-style <text>"
+    else
         echo -e "\033[1;36m$1\033[0m"
     fi
 }
@@ -44,12 +44,13 @@ export -f unknown-style
 
 # print usage message
 usage() {
-    echo "Usage: $0 [-d|--diff] [-u|--update] [-q|--qsyn <path to qsyn>]"
-    echo "  -d, --diff      diff the output of qsyn with the expected output"
-    echo "  -u, --update    update the expected output with the output of qsyn"
-    echo "  -q, --qsyn      path to qsyn executable"
+    echo "Usage: $0 [-d|--diff] [-u|--update] [-g|--gv <path to gv>]"
+    echo "  -d, --diff      diff the output of gv with the expected output"
+    echo "  -u, --update    update the expected output with the output of gv"
+    echo "  -g, --gv        path to gv executable"
     echo "  -v, --verbose   also report tests that pass"
     echo "  -s, --silent    do not report difference between execution result and reference"
+    echo "  -f, --full      execute the dofiles within the \"full\" folder (takes longer time)"
 }
 export -f usage
 
@@ -60,53 +61,60 @@ GV=./gv
 ACTION=""
 SILENT=0
 VERBOSE=0
+FULL=0
 POSITIONAL=()
+FULL_DIR=(full)
 
 while [[ $# -gt 0 ]]; do
     case $1 in
-        -d|--diff) 
-            if [ -n "$ACTION" ]; then
-                echo "Error: cannot specify multiple actions!!"
-                usage
-                exit 1
-            fi
-            ACTION="diff"
-            shift # argument
-            ;;
-        -u|--update) 
-            if [ -n "$ACTION" ]; then
-                echo "Error: cannot specify multiple actions!!"
-                usage
-                exit 1
-            fi
-            ACTION="update"
-            shift # argument
-            ;;
-        -q|--qsyn)
-            GV=$2;
-            shift # argument
-            shift # variable
-            ;;
-        -v|--verbose)
-            VERBOSE=1
-            shift # argument
-            ;;
-        -s|--silent)
-            SILENT=1
-            shift # argument
-            ;;
-        -h|--help)
-            usage
-            exit 0
-            ;;
-        -*|--*)
-            echo "Error: unknown option $1!!"
+    -d | --diff)
+        if [ -n "$ACTION" ]; then
+            echo "Error: cannot specify multiple actions!!"
             usage
             exit 1
-            ;;
-        *)
-            POSITIONAL+=("$1")
-            shift # argument
+        fi
+        ACTION="diff"
+        shift # argument
+        ;;
+    -u | --update)
+        if [ -n "$ACTION" ]; then
+            echo "Error: cannot specify multiple actions!!"
+            usage
+            exit 1
+        fi
+        ACTION="update"
+        shift # argument
+        ;;
+    -g | --gv)
+        GV=$2
+        shift # argument
+        shift # variable
+        ;;
+    -v | --verbose)
+        VERBOSE=1
+        shift # argument
+        ;;
+    -s | --silent)
+        SILENT=1
+        shift # argument
+        ;;
+    -h | --help)
+        usage
+        exit 0
+        ;;
+    -f | --full)
+        FULL=1
+        shift
+        ;;
+    -* | --*)
+        echo "Error: unknown option $1!!"
+        usage
+        exit 1
+        ;;
+    *)
+        POSITIONAL+=("$1")
+        shift # argument
+        ;;
     esac
 done
 
@@ -127,7 +135,11 @@ for arg in "${POSITIONAL[@]}"; do
     if [ -f "$arg" ]; then
         TESTS+=("$arg")
     elif [ -d "$arg" ]; then
-        for file in $(find $arg -regex ".*\.dofile" -type f); do
+        if [[ $FULL -eq 0 ]]; then
+            EXCLUDE_COMMAND="-type d -name $FULL_DIR -prune -o"
+        fi
+
+        for file in $(find $arg ${EXCLUDE_COMMAND} -regex ".*\.dofile" -type f); do
             if [ -f "$file" ]; then
                 TESTS+=("$file")
             fi
@@ -139,7 +151,7 @@ for arg in "${POSITIONAL[@]}"; do
     fi
 done
 
-# run dofile with qsyn and diff the output with the expected output
+# run dofile with gv and diff the output with the expected output
 
 ref-path() {
     local TEST=$1
@@ -147,7 +159,7 @@ ref-path() {
 }
 export -f ref-path
 
-# diff the output of qsyn with the reference output
+# diff the output of gv with the reference output
 dofile-result-same-with-ref() {
     local TEST=$1
     local VERBOSE=$2
@@ -155,7 +167,7 @@ dofile-result-same-with-ref() {
     local GV=$4
     local DIFF=$5
     local REF=$(ref-path $TEST)
-    
+
     DIFF_OUTPUT=$(OMP_WAIT_POLICY=passive $GV -file $TEST 2>&1 | $DIFF - $REF 2>&1)
 
     # if [ $? -eq 0 ]; then
@@ -167,7 +179,7 @@ dofile-result-same-with-ref() {
     else
         if [ ! -f $REF ]; then
             echo "  $(unknown-style '?') $REF"
-        else 
+        else
             echo "  $(fail-style '✗') $TEST"
         fi
         if [[ $SILENT -eq 0 ]]; then
@@ -193,10 +205,11 @@ update-dofile-ref() {
         touch $REF
     fi
 
-    DIFF_OUTPUT=$(OMP_WAIT_POLICY=passive $GV --no-version --qsynrc-path /dev/null --file $TEST 2>&1 | diff $REF -)
+    DIFF_OUTPUT=$(OMP_WAIT_POLICY=passive $GV -file $TEST 2>&1 | diff $REF -)
 
-    # update reference file if the output of qsyn is different from the reference
-    if [[ $? -eq 0 ]]; then
+    # update reference file if the output of gv is different from the reference
+    # if [[ $? -eq 0 ]]; then
+    if [ -z "$DIFF_OUTPUT" ]; then
         if [[ $VERBOSE -eq 1 ]]; then
             echo "  - $TEST"
             return 0
@@ -206,7 +219,7 @@ update-dofile-ref() {
         if [[ $? -eq 1 ]]; then
             echo "  $(fail-style !) $TEST"
             return 0
-        else 
+        else
             echo "  $(pass-style ↑) $TEST"
             return 1
         fi
@@ -217,7 +230,7 @@ export -f update-dofile-ref
 # diff dofiles and report result
 if [[ "$ACTION" == 'diff' ]]; then
     echo "> Testing dofiles..."
-    
+
     # run in parallel and count failures
     # parallel -j"$(nproc)" "dofile-result-same-with-ref {} $VERBOSE $SILENT $GV $DIFF" ::: "${TESTS[@]}"
     parallel -j"1" "dofile-result-same-with-ref {} $VERBOSE $SILENT $GV $DIFF" ::: "${TESTS[@]}"
@@ -234,7 +247,7 @@ elif [[ "$ACTION" == 'update' ]]; then
     echo "> Updating reference files..."
 
     # run in parallel and count updates
-    parallel -j"$(nproc)" "update-dofile-ref {} $VERBOSE $SILENT $GV" ::: "${TESTS[@]}"
+    parallel -j"1" "update-dofile-ref {} $VERBOSE $SILENT $GV" ::: "${TESTS[@]}"
 
     UPDATE_COUNT=$?
 
